AZURE_OPENAI_KEY = "F8cvPQQ5iKHG8NUJY0GbhH4Zxhll5BJQUMOapCLVoDQ6xX9V70tYJQQJ99BFACHYHv6XJ3w3AAAAACOGaJVI"
AZURE_OPENAI_ENDPOINT = "https://sanvi-mbf58gtv-eastus2.cognitiveservices.azure.com/"
AZURE_OPENAI_VERSION = "2024-12-01-preview"
AZURE_DEPLOYMENT_NAME = "gpt-4.1"

LANGSMITH_API_KEY = "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"
LANGCHAIN_PROJECT = "PromptCraft"
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
